name: mlops_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - seaborn=0.11.1
  - pandas=1.2.2
  - pytest=6.2.2
  - pip=20.3.3
  - git=2.30.2
  - pillow=8.1.2
  - pylint=2.7.4
  - autopep8=1.5.6
  - flake8=3.9.0
  - pip:
    - click==7.1.2
    - cycler==0.10.0
    - Flask==1.1.2
    - gunicorn==20.0.4
    - itsdangerous==1.1.0
    - Jinja2==2.11.3
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - MarkupSafe==1.1.1
    - matplotlib==3.3.4
    - numpy==1.20.1
    - Pillow==8.1.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2021.1
    - scikit-learn==0.24.1
    - scipy==1.6.1
    - six==1.15.0
    - sklearn==0.0
    - threadpoolctl==2.1.0
    - Werkzeug==1.0.1